services:
    srpsdiesel:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8081:80
        restart: always
    directus:
        image: directus/directus:11
        ports:
            - 8055:8055
        restart: always
        volumes:
            - ./database:/directus/database
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
        environment:
            SECRET: "T&|A~1)9!V8.R+:o#C:&ZB[hT0&J;F"
            ADMIN_EMAIL: "admin@example.com"
            ADMIN_PASSWORD: "purple"
            DB_CLIENT: "mysql"
            DB_HOST: "mysql"
            DB_PORT: "3306"
            DB_DATABASE: "directus"
            DB_USER: "root"
            DB_PASSWORD: "purple"
            WEBSOCKETS_ENABLED: "true"
            CORS_ENABLED: "true"
            CORS_ORIGIN: "*"
    directus2:
        image: directus/directus:11
        ports:
            - 8059:8055
        restart: always
        volumes:
            - ./database2:/directus/database
            - ./uploads2:/directus/uploads
            - ./extensions2:/directus/extensions
        environment:
            SECRET: "XT&|A~1)9!V8.R+:o#C:&ZB[hT0&J;F"
            ADMIN_EMAIL: "admin@example.com"
            ADMIN_PASSWORD: "purple"
            DB_FILENAME: "/directus/database/database.sqlite"
            WEBSOCKETS_ENABLED: "true"
            CORS_ENABLED: "true"
            CORS_ORIGIN: "*"
            SESSION_COOKIE_NAME: "srpsmpd2"
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'purple'
            MYSQL_USER: 'directususer'
            MYSQL_PASSWORD: 'purple'
            MYSQL_DATABASE: 'directus'
        restart: always
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3310:3306

